env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - eslint:recommended
  - plugin:solid/typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  project: tsconfig.json
  sourceType: module
plugins:
  - prettier
  - simple-import-sort
  - solid
  - "@typescript-eslint"
rules:
  prettier/prettier:
    - error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
settings:
  import/resolver:
    node:
      extensions:
        - .tsx
